# Generated by Django 5.1.3 on 2024-11-16 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aircraft_team_assembly_inventoryalert_part_user_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryalert',
            name='aircraft',
        ),
        migrations.DeleteModel(
            name='Assembly',
        ),
        migrations.DeleteModel(
            name='InventoryAlert',
        ),
    ]
