# Generated by Django 5.1.3 on 2024-11-17 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_inventoryalert_aircraft_delete_assembly_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='aircraft',
        ),
        migrations.AddField(
            model_name='aircraft',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='part_ids',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aircraft', to='core.part'),
        ),
        migrations.AddField(
            model_name='part',
            name='team_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='core.team'),
        ),
    ]
